language: node_js
node_js:
- '6'
install:
- npm install -g firebase-tools
- npm i
before_script:
- npm run test
script:
- npm run build
after_success:
- firebase deploy --token $FIREBASE_TOKEN
notifications:
  slack:
    secure: cItL0e+drdb5DYd7Cu37FNbTmp0mAbRGgMTYwhOp5llBimMUHlREVqDkRa4jySqHMbApeafzlBpX41+JEsusmtuSFKAUF3x6dkS2Xv0Ksl4j8fVRSbeNWjLuQjeTH/OsrUD7I76NtvaZ7VwvMKINeHjVt5yWGtDOPytXExr4ghDPvtSIvf4kuWv1ZfAHemNXvu0omhmvFKBi3wU4hZiO/qGBNqGpAGcELHelhSUIx6zvixuy9IW24GkrfuB0E/U+BIqtIBmZHZVV33Txxb9QSq35NCM9DMknuiNDlUt42uH35zErcKlVceZTBJVlS+7SoqggIYzvp5ewqAhaOz2FdVpHw++GuzeKdpNXd/vnaMBGeUE6ZQUG/w/17gbd04dv3Bg0K6eSsWBi31BcCHYq5IadQG7OkDjn59wTKtCZX8fZ1kckMJnBCb7qT8rOlCStyHwQMyAd4swO22c0n+K7E5UpyNk9wNqz+pelGfuha5+0qHN9uR7w7bKN+Ud1Acl25CvDvf0bq6p0Xudgxf32l4aYVlhT/1Fp34ViDfK+iWrnNXmCEGc32REXNbiTdIVFihzjbklP/gOSBm8iL4nSh40Vc9AP0jzvxgJvWuHZplOk3fCDFE3nnAecoNjaIo7Ugtq7BvJoHkm73tdmAt6Eb0YoIVarv56fQJ/OcY4DhAU=
