language: node_js
node_js:
  - "6"

install:
  - npm install -g firebase-tools
  - npm i

before_script:
  - npm run test

script:
  - npm run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
